export const colors = {
  PRIMARY : "",
  PRIMARY_VARIANT : "",
  SECONDARY : "",
  SECONDARY_VARIANT : "",
  COMPLIMENTARY_RED : "#FF5544",
  COMPLIMENTARY_BLUE : "#A6D3F2",
  COMPLIMENTARY_YELLOW : "#F7D780",
  COMPLIMENTARY_GREEN : "#AFC3AB",
  FONT_PRIMARY : "#000000",
  FONT_SECONDARY : "#ffffff",
  BACKGROUND : "#ffffff",
  IMAGE : "#CEE1F4"
}